
TYPE
	AxisParam : 	STRUCT 
		ManualDistance : LREAL := 500; (*Setting distance of the belt move [mm]*)
		ManualVelocity : REAL := 50; (*Value of velocity [mm/s]*)
	END_STRUCT;
	ManualStepsEnum : 
		(
		MANUAL_START := 10,
		MANUAL_WAIT := 20,
		MANUAL_ACTUATOR_DOSING := 30,
		MANUAL_ACTUATOR_SORTING := 40,
		MANUAL_ACTUATOR_BOTH := 50,
		MANUAL_ACTUATOR_NONE := 60,
		MANUAL_BELT_SET_ADDITIVE := 70,
		MANUAL_BELT_MOVE_ADDITIVE := 80,
		MANUAL_BELT_SET_VELOCITY := 90,
		MANUAL_BELT_MOVE_VELOCITY := 100,
		MANUAL_BELT_MOVE_ADDITIVE1 := 110
		);
END_TYPE
