
TYPE
	ManualStepsEnum : 
		(
		MANUAL_START := 10,
		MANUAL_WAIT := 20,
		MANUAL_ACTUATOR_DOSING := 30,
		MANUAL_ACTUATOR_SORTING := 40,
		MANUAL_ACTUATOR_BOTH := 50,
		MANUAL_ACTUATOR_NONE := 60,
		MANUAL_BELT_MOVE := 70
		);
END_TYPE
